// export default function RecentTable({ files }) {
//   return (
//     <div className="bg-white rounded-2xl shadow-sm p-6">
//       <div className="flex justify-between items-center mb-4">
//         <h2 className="text-lg font-semibold">Recent Extractions</h2>
//       </div>

//       {files.length === 0 ? (
//         <p className="text-gray-500">No invoices uploaded yet.</p>
//       ) : (
//         <table className="w-full text-left">
//           <thead>
//             <tr className="text-sm text-gray-500">
//               <th className="pb-3">Vendor</th>
//               <th className="pb-3">Status</th>
//               <th className="pb-3">Amount</th>
//             </tr>
//           </thead>

//           <tbody>
//             {files.map((file) => (
//               <tr key={file.id} className="border-t">
//                 <td className="py-3 font-medium">
//                   {file.vendor || file.filename}
//                 </td>

//                 <td className="py-3">
//                   <span className="px-3 py-1 bg-green-100 text-green-700 rounded-full text-sm">
//                     {file.status}
//                   </span>
//                 </td>

//                 <td className="py-3 font-semibold">
//                   ${file.total || 0}
//                 </td>
//               </tr>
//             ))}
//           </tbody>
//         </table>
//       )}
//     </div>
//   );
// }

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export default function RecentTable({ files = [] }) {

  // Clean OCR numbers
  const cleanNumber = (value) => {
    if (!value) return 0;

    const cleaned = value
      .toString()
      .replace(/\s+/g, "")
      .replace(/[^\d.]/g, "");

    return parseFloat(cleaned) || 0;
  };

  const downloadReceipt = (file) => {

    const pdf = new jsPDF();

    const pageWidth = pdf.internal.pageSize.getWidth();

    pdf.setFontSize(18);
    pdf.text("Digitized Receipt", pageWidth / 2, 20, { align: "center" });

    pdf.setFontSize(12);
    pdf.text(`Vendor: ${file.vendor}`, 20, 40);
    pdf.text(`Date: ${file.date}`, 20, 48);
    pdf.text(`File: ${file.filename}`, 20, 56);

    const tableData = [];

    if (file.items && file.items.length > 0) {

      file.items.forEach((item) => {

        const qty = cleanNumber(item.quantity) || 1;
        const price = cleanNumber(item.price);
        const total = cleanNumber(item.total) || qty * price;

        tableData.push([
          item.name,
          qty,
          `$${price.toFixed(2)}`,
          `$${total.toFixed(2)}`
        ]);

      });

    }

    autoTable(pdf, {
      startY: 70,
      head: [["Item", "Qty", "Price", "Total"]],
      body: tableData,
      theme: "grid",
      styles: {
        fontSize: 10,
        cellPadding: 4,
        overflow: "linebreak"
      },
      columnStyles: {
        0: { cellWidth: 95 },
        1: { cellWidth: 20, halign: "center" },
        2: { cellWidth: 30, halign: "right" },
        3: { cellWidth: 30, halign: "right" }
      }
    });

    // Total section
    const totalAmount = cleanNumber(file.total);

    const finalY = pdf.lastAutoTable.finalY + 10;

    pdf.setFontSize(12);
    pdf.text(
      `Total Amount: $${Number(totalAmount).toLocaleString("en-IN")}`,
      pageWidth / 2,
      finalY,
      { align: "center" }
    );

    // Footer
    pdf.setFontSize(10);
    pdf.text(
      "Generated by Receipt Invoice Digitizer",
      pageWidth / 2,
      finalY + 15,
      { align: "center" }
    );

    pdf.text(
      "support@gmail.com",
      pageWidth / 2,
      finalY + 22,
      { align: "center" }
    );

    pdf.save(`${file.filename}_digitized_receipt.pdf`);
  };


  return (
    <div className="bg-white dark:bg-slate-800 rounded-2xl shadow-sm p-6">

      <h2 className="text-lg font-semibold mb-4">
        Recent Extractions
      </h2>

      {files.length === 0 ? (
        <p className="text-gray-500 dark:text-gray-400">
          No files processed yet.
        </p>
      ) : (
        <div className="overflow-x-auto">

          <table className="w-full text-sm">

            <thead>
              <tr className="border-b border-gray-200 dark:border-slate-700">
                <th className="text-left py-2 pr-4">File</th>
                <th className="text-left py-2 pr-4">Vendor</th>
                <th className="text-left py-2 pr-4">Total</th>
                <th className="text-left py-2 pr-4">Date</th>
                <th className="text-left py-2">Action</th>
              </tr>
            </thead>

            <tbody>

              {files.map((file) => (
                <tr
                  key={file.id}
                  className="border-b border-gray-100 dark:border-slate-700"
                >

                  <td className="py-3 pr-4 font-medium">
                    {file.filename}
                  </td>

                  <td>{file.vendor}</td>

                  <td>${cleanNumber(file.total).toFixed(2)}</td>

                  <td>{file.date}</td>

                  <td>
                    <button
                      onClick={() => downloadReceipt(file)}
                      className="bg-blue-600 hover:bg-blue-700 text-white px-3 py-1 rounded text-xs"
                    >
                      Download
                    </button>
                  </td>

                </tr>
              ))}

            </tbody>

          </table>

        </div>
      )}

    </div>
  );
}